import { IDropdownSelectOption } from "../../components/dropdownSelect";

export const intlLanguages: IDropdownSelectOption[] = [
    { value: "English", label: "English", default: true, symbol: "🇺🇸" },
    { value: "Spanish", label: "Español", symbol: "🇪🇸" },
    { value: "French", label: "Français", symbol: "🇫🇷" },
    { value: "German", label: "Deutsch", symbol: "🇩🇪" },
    { value: "Italian", label: "Italiano", symbol: "🇮🇹" },
    { value: "Japanese", label: "日本語", symbol: "🇯🇵" },
    { value: "Korean", label: "한국어", symbol: "🇰🇷" },
    { value: "Portuguese", label: "Português", symbol: "🇵🇹" },
    { value: "Russian", label: "Русский", symbol: "🇷🇺" },
    { value: "Chinese", label: "中文", symbol: "🇨🇳" },
    { value: "Persian", label: "فارسی", symbol: "🇮🇷" },
    { value: "Arabic", label: "العربية", symbol: "🇸🇦" },
    { value: "Hindi", label: "हिन्दी", symbol: "🇮🇳" },
    { value: "Bengali", label: "বাংলা", symbol: "🇧🇩" },
    { value: "Indonesian", label: "Bahasa Indonesia", symbol: "🇮🇩" },
    { value: "Urdu", label: "اردو", symbol: "🇵🇰" },
    { value: "Turkish", label: "Türkçe", symbol: "🇹🇷" },
    { value: "Vietnamese", label: "Tiếng Việt", symbol: "🇻🇳" },
    { value: "Thai", label: "ไทย", symbol: "🇹🇭" },
    { value: "Malay", label: "Bahasa Melayu", symbol: "🇲🇾" },
    { value: "Dutch", label: "Nederlands", symbol: "🇳🇱" },
    { value: "Swedish", label: "Svenska", symbol: "🇸🇪" },
    { value: "Danish", label: "Dansk", symbol: "🇩🇰" },
    { value: "Norwegian", label: "Norsk", symbol: "🇳🇴" },
    { value: "Finnish", label: "Suomi", symbol: "🇫🇮" },
    { value: "Polish", label: "Polski", symbol: "🇵🇱" },
    { value: "Romanian", label: "Română", symbol: "🇷🇴" },
    { value: "Czech", label: "Čeština", symbol: "🇨🇿" },
    { value: "Greek", label: "Ελληνικά", symbol: "🇬🇷" },
    { value: "Hungarian", label: "Magyar", symbol: "🇭🇺" },
    { value: "Bulgarian", label: "Български", symbol: "🇧🇬" },
    { value: "Croatian", label: "Hrvatski", symbol: "🇭🇷" },
    { value: "Serbian", label: "Српски", symbol: "🇷🇸" },
    { value: "Slovak", label: "Slovenčina", symbol: "🇸🇰" },
    { value: "Slovenian", label: "Slovenščina", symbol: "🇸🇮" },
    { value: "Estonian", label: "Eesti", symbol: "🇪🇪" },
    { value: "Latvian", label: "Latviešu", symbol: "🇱🇻" },
    { value: "Lithuanian", label: "Lietuvių", symbol: "🇱🇹" },
];
